name: General Feedback or Question
description: For anything else not covered by the other templates.
title: "[Feedback] Your title here"
labels: ["question", "feedback"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        💬 Use this form for questions, suggestions, or anything else related to this project.

  - type: textarea
    id: message
    attributes:
      label: What would you like to share?
      placeholder: e.g., Can I add X? Can you clarify Y? I have a suggestion...
    validations:
      required: true
