name: Report Unfriendly Bug Bounty Program
description: Submit a case where a company failed to reward, respond, or ghosted after a report.
title: "[Report] Company Name - Issue Summary"
labels: ["report"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🐞 Thank you for submitting a report.  
        Please fill in as many details as possible to help the community.

  - type: input
    id: company
    attributes:
      label: Company Name
      description: Name of the company or program involved
      placeholder: example.com
    validations:
      required: true

  - type: checkboxes
    id: issue_type
    attributes:
      label: What happened?
      description: Select one or more that best describe your experience.
      options:
        - label: Silent patch (company fixed the bug but didn’t inform or reward)
        - label: No bounty or swag given
        - label: Ghosted after submission
        - label: Other (please explain in summary)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary of the Incident
      description: Briefly describe what happened
      placeholder: |
        e.g. I reported an RCE bug on 12 March, they patched it silently on 20 March, and never responded.
    validations:
      required: true

  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: Important dates like report date, last contact, patch date, etc.
      placeholder: |
        - Report sent: DD/MM/YYYY
        - Response received: DD/MM/YYYY
        - Last contact: DD/MM/YYYY
        - Patch date (if applicable): DD/MM/YYYY
    validations:
      required: true

  - type: textarea
    id: proof
    attributes:
      label: Proof or Evidence
      description: Add links to screenshots, writeups, tweets, or other proof (if any)
      placeholder: https://example.com/my-report
    validations:
      required: true

  - type: input
    id: researcher_handle
    attributes:
      label: Your Handle (optional)
      description: Your GitHub, Twitter, or LinkedIn handle (optional)
      placeholder: "@yourhandle"
    validations:
      required: false

  - type: checkboxes
    id: program_status
    attributes:
      label: Has the company shut down their bug bounty program?
      options:
        - label: Yes, the program has been shut down.
        - label: No, the program is still active.
        - label: I am not sure about the status.
    validations:
      required: true

  - type: checkboxes
    id: agreement
    attributes:
      label: Confirmation
      options:
        - label: I confirm this is based on my personal experience and is respectful.
          required: true
    validations:
      required: true
